-- Per-week phase labels for the active plan (base|build|peak|taper, one per plan
-- week). Generated by Claude at plan time; null for legacy plans (a heuristic
-- fallback derives phases client-side). Shape: jsonb array of strings.
alter table training_plans add column if not exists week_phases jsonb;
